spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: password


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

  liquibase:
    change-log: classpath:liquibase/master.xml
    contexts: "develop"